### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dekablade01** [nawaz4225/NimbleCodeChallenge#2]
- Lack of testing
- `MainPageVM` is not testable since `APIClient` is singleton. 
- `APIClient` is not testable.

**Comment by nawaz4225** [comment]
Impressed with your coding review as I was expecting that. :)

Due to time constraints and very busy week in office I tried to make that quick and keep it short.

But now I can work on that and make it more clean and testable.

There are 2 ways to do that 1 I can simply make that singelton testable by introducing some kinf of reset method in init which we will be able to use in tearDown to reinstantiate the instance of APIClient for every test case. which will make both `MainPageVM` and `APIClient` testable.

2nd I can write more clean structured NetworkLayer which uses dependency Injections. and then we can mack this layer for tests (That would be better approach).

I will try to implement 1 as soon as I get some time this weekend

**Comment by nawaz4225** [comment]
modified `APIClient`.
removed sharedInstance.
now its more testable and can be mocked in test module.
