### ISSUE TITLE
SourceCode

### ISSUE THREAD

**Issue by dekablade01** [nawaz4225/NimbleCodeChallenge#3]
- `UIKit` should not be imported in `ViewModel`
- Access Modifiers are not organized. All functions and variable are all `internal`
- There are some `IBOutlet` use `weak` and some use `strong` reference. 
- Creating `ViewController` with `rawString` is risky. It would be better if there’s a factory to instantiateViewController. 
- Adding `l` after the image name to convert it to a large image should not be done in `ViewController` 
- `APIManager` should not hold `authModel` 
- `Codable` is not applied. Request parameters are assembled by the dictionary. 
- Decoding JSON should not be done in the ViewModel layer. 
- `print` should be removed. 
- `APIClient` doesn’t need `[weak self]` since it is a singleton.

**Comment by nawaz4225** [comment]
- Absolutely right. I had a plan to add `PageVCManager` to handle that navigation indexes but de to time constraints i was not able to refactor that in end. its done now.
- I try to use `IBOutlets` weak for `UIViews` and strong for `NSConstraints`.

- factory to instantiateViewController. I have added that. to use we just have to use same ClassName and Storyboard identifier for ViewController. wrong identifier gives fatal error with proper message instead of a crash.

- Added `enum` for image quality types and used that in `CachedImageView`. that now looks more promising.

- print in `APIClient` is removeable as there is check in function params with default value `true`. `isPrint: Boolean = false` will not print results.

- I will be trying to make that singelton testable with some kind of reset function which we can use in tearDown to reinstantiate for every test. so i think in this case we will need [weak self] for tests. 

- APIManager should not hold authModel(in progress)

- Codable is not applied. Request parameters are assembled by the dictionary.(in progress)

**Comment by dekablade01** [comment]
- For `IBOutlets` do you have a reason why `UIViews` should be `weak` but `NSConstraints` should be `strong`? Since the Apple engineer said in WWDC2015 `IBOutlets` should be `strong` 🤔
- For `CachedImageView` what if you what to use it for any image URL provider else. What are you gonna put for the `quality` parameter? This class is now tight to this SurveyService.  Is it going to be better if you do it on the model layer? 🤔
- For printing request components, what if you released the build without changing it to `false` then everyone will be able to see the token. 🤔
- For `makeApiRequest`, rather than passing tuple of (Data?, NetworkingError?) which one of them will be `nil`, Is it going to be better if you use `Swift.Result<Data, NetworkingError>` ?

**Comment by nawaz4225** [comment]
well thats an interesting point. after apple recommending to use `strong` win WWDC2015 and use `weak` only to avoid retain cycles. but after that recommendation there is still lots of discussin about that. 

with `strong` you gain control over the lifecycle of object. but with `weak` we don't have control over the lifecycle of object. it is destroyed by arc when there is no `strong` refrence pointing to this object.

in case of UIViews in View Controllers there is not that big difference between using `weak` or `strong` but there are few points we need to care about while using `weak` or `strong`.

as I mentioned earlier `weak` refrence only got deallocated from memory when there is no `strong` refrence pointoing to that. in ViewControllers we have a strong refrence of parent view `open var view: UIView!` and all the other UIViews are subviews to this. so we can use `weak` because that that parentview will always have refrence to subviews in ViewController lifecycle. 
although using `strong` will also be fine in that case as apple suggest. but using `strong` everywhere can lead to retain cycles which is very bad. using `weak` gurantees no retain cycles. 
although we need to use `strong` if we are adding or removing any subview into viewcontroller at run time and with constrains if we are activating or deactiving constraints. 

I have never faced issues with using `weak` with `IBOutlets` but have countered issues using `weak` with `NSConstraints` in `TableViewCell`.

**Comment by nawaz4225** [comment]
How I see `CachedImageView` it is not that tight to SurveyService. 

`loadImage(urlString: String, quality: ImageQualityFactory, bgColor: UIColor? = UIColor.gray)`

to 
`loadImage(urlString: String, quality: ImageQualityFactory = .low, bgColor: UIColor? = UIColor.gray)`

will make this work for all other URLs. but then there might be a question that what if we wants to use other image quality Char(Like 'l' in SurveyService) for any other Service.

```
enum ImageQualityFactory: String {
    case low = ""
    case high = "l"
}
```

We can do this by adding more case for every service there. but that would be little bad if we like have lot of services and every service having different appending Char. in this case solution you are offering with Models will be the solution. I will add a protocol which can be used with different models to get it done more efficently.

**Comment by nawaz4225** [comment]
Its always better to remove print statements before commenting the code to avoid this. My bad I ignored that while commenting.

**Comment by nawaz4225** [comment]
added 

`enum MyResult<T, E: Error>` to replace tuple in `makeApiRequest`

**Comment by dekablade01** [comment]
> How I see `CachedImageView` it is not that tight to SurveyService.
> 
> `loadImage(urlString: String, quality: ImageQualityFactory, bgColor: UIColor? = UIColor.gray)`
> 
> to
> `loadImage(urlString: String, quality: ImageQualityFactory = .low, bgColor: UIColor? = UIColor.gray)`
> 
> will make this work for all other URLs. but then there might be a question that what if we wants to use other image quality Char(Like 'l' in SurveyService) for any other Service.
> 
> ```
> enum ImageQualityFactory: String {
>     case low = ""
>     case high = "l"
> }
> ```
> 
> We can do this by adding more case for every service there. but that would be little bad if we like have lot of services and every service having different appending Char. in this case solution you are offering with Models will be the solution. I will add a protocol which can be used with different models to get it done more efficently.

But what if someone has a tiny imageURL and want to use this function, he/she may think that `oh this CachedImageView can improve image quality by just passing the ImageQualityFactory`. How does it not tight ? 

Is it going to be better if ??

```swift
extension Survey { 

   var largeImageURL: URL? { return URL(string: imageURL.absoluteString + "l") }

}
```

**Comment by dekablade01** [comment]
> well thats an interesting point. after apple recommending to use `strong` win WWDC2015 and use `weak` only to avoid retain cycles. but after that recommendation there is still lots of discussin about that.
> 
> with `strong` you gain control over the lifecycle of object. but with `weak` we don't have control over the lifecycle of object. it is destroyed by arc when there is no `strong` refrence pointing to this object.
> 
> in case of UIViews in View Controllers there is not that big difference between using `weak` or `strong` but there are few points we need to care about while using `weak` or `strong`.
> 
> as I mentioned earlier `weak` refrence only got deallocated from memory when there is no `strong` refrence pointoing to that. in ViewControllers we have a strong refrence of parent view `open var view: UIView!` and all the other UIViews are subviews to this. so we can use `weak` because that that parentview will always have refrence to subviews in ViewController lifecycle.
> although using `strong` will also be fine in that case as apple suggest. but using `strong` everywhere can lead to retain cycles which is very bad. using `weak` gurantees no retain cycles.
> although we need to use `strong` if we are adding or removing any subview into viewcontroller at run time and with constrains if we are activating or deactiving constraints.
> 
> I have never faced issues with using `weak` with `IBOutlets` but have countered issues using `weak` with `NSConstraints` in `TableViewCell`.

Yup, you're right this is not a big deal.

**Comment by nawaz4225** [comment]
> ```swift
> extension Survey { 
> 
>    var largeImageURL: URL? { return URL(string: imageURL.absoluteString + "l") }
> 
> }
> ```

yeah exactly that going to be much better I have already implmented `ImageResolutionable` to do something similar.
